### ISSUE TITLE
Number of Kernels

### ISSUE THREAD

**Issue by twang15** [mohamso/optewe#1]
Hi Mohammed,

In your SC paper, it says "In total, 25 kernels are computed per iterations."
So I suppose there should be 25 OMP kernels in the code.
However, a grep result only find 15.

Which one is right? and why?

Thanks.

./src/differentiators.cc:12:  #pragma omp parallel for num_threads(nthreads)
./src/differentiators.cc:31:  #pragma omp parallel for num_threads(nthreads)
./src/differentiators.cc:50:  #pragma omp parallel for num_threads(nthreads)
./src/differentiators.cc:69:  #pragma omp parallel for num_threads(nthreads)
./src/differentiators.cc:88:  #pragma omp parallel for num_threads(nthreads)
./src/differentiators.cc:107:  #pragma omp parallel for num_threads(nthreads)
./src/main.cc:114:  #pragma omp parallel for num_threads(nthreads)
./src/mem_utils.cc:10:#pragma omp parallel for
./src/step_forward.cc:14:  #pragma omp parallel for num_threads(nthreads)
./src/step_forward.cc:30:  #pragma omp parallel for num_threads(nthreads)
./src/step_forward.cc:47:  #pragma omp parallel for num_threads(nthreads)
./src/step_forward.cc:64:  #pragma omp parallel for num_threads(nthreads)
./src/step_forward.cc:81:  #pragma omp parallel for num_threads(nthreads)
./src/step_forward.cc:98:  #pragma omp parallel for num_threads(nthreads)
./src/step_forward.cc:116:  #pragma omp parallel for num_threads(nthreads)

**Comment by phate** [comment]
The paper is misleading in this respect. There are 25 kernel invocations per iteration, but some of those are to the same kernel.

**Comment by twang15** [comment]
Thanks a lot, Nico.

Could you please let me know how to check whether the result of a run is correct or not?

**Comment by phate** [comment]
I just had a look at our NTNU repository, and I did not find a script that checks for the correctness of a run. I am afraid I cannot help you further with this. Mohammed is the only one who can answer this question, as he was the one performing the experiments. Sorry!

**Comment by mohamso** [comment]
Hi, Twang15.

I did not see this until now as I don't have Github notification turned on.

The are two ways to check the correctness.
Please check the new "Verification" section in the README.md file.
